name: Mirror and run GitLab CI

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.igem.org/2023/munichbioinformatics"
      env:
        FOLLOW_TAGS: "true"
        FORCE_PUSH: "true"
        GITLAB_HOSTNAME: "gitlab.igem.org"
        GITLAB_USERNAME: "FinnLueth"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "https://gitlab.igem.org/2023/munichbioinformatics"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
